#   Display available recipes
default:
    @ just --list

alias i := install

#   Update poetry dependencies
install:
    poetry install

alias b := build_graphs

#   Update graphs on the markdown file
build_graphs: install
    poetry run kde
    poetry run boxplot
